Repository Devcourse-BE6-8-1-Team10/Backend, pull requests merged in 2025-07, with the labels that each got.

#43 [fix] githubignore 처리#1
  .gitignore
  .gradle/8.13/checksums/checksums.lock
  .gradle/8.13/checksums/md5-checksums.bin
  .gradle/8.13/checksums/sha1-checksums.bin
  .gradle/8.13/executionHistory/executionHistory.bin
  .gradle/8.13/executionHistory/executionHistory.lock
  .gradle/8.13/fileChanges/last-build.bin
  .gradle/8.13/fileHashes/fileHashes.bin
  .gradle/8.13/fileHashes/fileHashes.lock
  .gradle/8.13/fileHashes/resourceHashesCache.bin
  .gradle/8.13/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/.gitignore
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/vcs.xml
  build/classes/java/main/com/example/demo/BackendApplication.class
  build/classes/java/main/com/example/demo/TestClass.class
  build/classes/java/main/com/example/demo/order/controller/DummyController.class
  build/classes/java/main/com/example/demo/order/entity/DummyEntity.class
  build/classes/java/main/com/example/demo/order/repository/DummyRepository.class
  build/classes/java/main/com/example/demo/order/service/DummyService.class
  build/classes/java/test/com/example/demo/TestClassTest.class
  build/reports/problems/problems-report.html
  build/reports/tests/test/classes/com.example.demo.TestClassTest.html
  build/reports/tests/test/css/base-style.css
  build/reports/tests/test/css/style.css
  build/reports/tests/test/index.html
  build/reports/tests/test/js/report.js
  build/reports/tests/test/packages/com.example.demo.html
  build/resources/main/application-dev.yml
  build/resources/main/application-prod.yml
  build/resources/main/application-test.yml
  build/resources/main/application.yml
  build/test-results/test/TEST-com.example.demo.TestClassTest.xml
  build/test-results/test/binary/output.bin
  build/test-results/test/binary/output.bin.idx
  build/test-results/test/binary/results.bin
  build/tmp/compileJava/compileTransaction/stash-dir/DummyRepository.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  build/tmp/compileTestJava/previous-compilation-data.bin
Labels: fix

#50 [refactor] 폴더 구조 변경 #1
  src/main/java/com/back/BackApplication.java
  src/main/java/com/back/global/entity/BaseEntity.java
  src/main/java/com/back/global/entity/BaseEntityWithTime.java
  src/main/java/com/example/demo/TestClass.java
  src/main/java/com/example/demo/order/controller/DummyController.java
  src/main/java/com/example/demo/order/service/DummyService.java
  src/main/java/com/example/order/controller/DummyController.java
  src/main/java/com/example/order/entity/DummyEntity.java
  src/main/java/com/example/order/repository/DummyRepository.java
  src/main/java/com/example/order/service/DummyService.java
  src/test/java/com/example/demo/TestClassTest.java
Labels: refactor

#59 [feat] 멤버 Entity 구현#1
  src/main/java/com/back/domain/member/controller/MemberController.java
  src/main/java/com/back/domain/member/entity/Member.java
  src/main/java/com/back/domain/member/repository/MemberRepository.java
  src/main/java/com/back/domain/member/service/MemberService.java
Labels: feat

#61 [feat] 유저 DTO 구현#1
  src/main/java/com/back/domain/member/dto/MemberDto.java
  src/main/java/com/back/domain/member/dto/MemberWithAuthDto.java
  src/main/java/com/back/domain/member/entity/Member.java
Labels: feat

#65 [feat] (메뉴)상품 단건 조회#1
  src/main/java/com/back/domain/order/dto/OrderDto.java
  src/main/java/com/back/domain/product/controller/ProductController.java
  src/main/java/com/back/domain/product/service/ProductService.java
  src/test/java/com/back/domain/product/controller/ProductControllerTest.java
Labels: feat

#66 [feat] 멤버 추가 (회원가입) 구현 #1
  src/main/java/com/back/domain/member/member/controller/MemberController.java
  src/main/java/com/back/domain/member/member/repository/MemberRepository.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/global/aspect/ResponseAspect.java
  src/main/java/com/back/global/exception/ServiceException.java
  src/main/java/com/back/global/globalExceptionHandler/GlobalExceptionHandler.java
  src/main/java/com/back/global/rsData/RsData.java
  src/main/java/com/example/order/controller/DummyController.java
  src/main/java/com/example/order/entity/DummyEntity.java
  src/main/java/com/example/order/repository/DummyRepository.java
  src/main/java/com/example/order/service/DummyService.java
  src/test/java/com/back/domain/member/member/controller/MemberControllerTest.java
  src/test/java/com/back/domain/product/controller/ProductControllerTest.java
Labels: feat

#69 [fix] RsData 관련 충돌 수정
  src/main/java/com/back/domain/product/controller/ProductController.java
Labels: fix

#71 [feat]: 메뉴(상품) 수정 기능#1
  src/main/java/com/back/domain/product/controller/ProductController.java
  src/main/java/com/back/domain/product/entity/Product.java
  src/main/java/com/back/domain/product/service/ProductService.java
  src/test/java/com/back/domain/product/controller/ProductControllerTest.java
Labels: feat

#73 [refactor] Spring Security 설정
  build.gradle
  src/main/java/com/back/domain/member/member/controller/MemberController.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/member/member/service/AuthTokenService.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/global/app/AppConfig.java
  src/main/java/com/back/global/initData/BaseInitData.java
  src/main/java/com/back/global/rq/Rq.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/CustomUserDetailsService.java
  src/main/java/com/back/global/security/SecurityConfig.java
  src/main/java/com/back/global/security/SecurityUser.java
  src/main/java/com/back/global/springDoc/SpringDocConfig.java
  src/main/java/com/back/standard/util/Ut.java
  src/main/resources/application.yml
  src/test/java/com/back/domain/member/member/controller/MemberControllerTest.java
Labels: refactor

#74 fix : 타입 오류 수정
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
Labels: fix

#68 [feat] 주문 생성#1
  src/main/java/com/back/domain/order/controller/OrderController.java
  src/main/java/com/back/domain/order/dto/OrderDto.java
  src/main/java/com/back/domain/order/dto/OrderDtoWithSpecific.java
  src/main/java/com/back/domain/order/dummy/Dummy.java
  src/main/java/com/back/domain/order/entity/Order.java
  src/main/java/com/back/domain/order/entity/OrderItem.java
  src/main/java/com/back/domain/order/repository/OrderRepository.java
  src/main/java/com/back/domain/order/service/OrderService.java
  src/test/java/com/back/domain/order/controller/OrderControllerTest.java
Labels: feat

#83 [feat] 회원의 주소 조회 #1
  src/main/java/com/back/domain/member/address/controller/AddressController.java
  src/main/java/com/back/domain/member/address/service/AddressService.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/test/java/com/back/domain/member/address/controller/AddressControllerTest.java
Labels: feat

#84 [feat] 주소 Entity 삭제 기능 #1
  src/main/java/com/back/domain/member/address/controller/AddressController.java
  src/main/java/com/back/domain/member/address/service/AddressService.java
  src/test/java/com/back/domain/member/address/controller/AddressControllerTest.java
Labels: feat

#85 [feat] 멤버 삭제(회원 탈퇴) 구현#1
  src/main/java/com/back/domain/member/member/controller/MemberController.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/member/member/service/AuthTokenService.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/global/initData/DevInitData.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/main/java/com/back/global/rq/Rq.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/security/CustomUserDetailsService.java
  src/main/java/com/back/global/security/SecurityUser.java
  src/test/java/com/back/domain/member/member/controller/MemberControllerTest.java
Labels: feat

#86 [feat] 회원 정보 조회 #1
  src/main/java/com/back/domain/member/member/controller/MemberController.java
  src/main/java/com/back/domain/member/member/dto/MemberUpdateDto.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/test/java/com/back/domain/member/address/controller/AddressControllerTest.java
  src/test/java/com/back/domain/member/member/controller/MemberControllerTest.java
Labels: feat

#92 [feat] CORS 처리#1
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
  src/main/java/com/back/global/webMvc/WebConfig.java
Labels: feat

#94 [hotfix] ProductControllerTest 수정
  src/test/java/com/back/domain/product/controller/ProductControllerTest.java
Labels: fix

#95 [refactor] BaseEntity 삭제
  src/main/java/com/back/domain/order/entity/Order.java
  src/main/java/com/back/domain/order/entity/OrderItem.java
  src/main/java/com/back/domain/product/entity/Product.java
  src/main/java/com/back/global/entity/BaseEntity.java
  src/main/java/com/back/global/entity/BaseEntityWithTime.java
Labels: refactor

#97 [refactor] Member Entity에 Builder 패턴 도입 #1
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/global/rq/Rq.java
  src/main/java/com/back/global/security/CustomAuthenticationFilter.java
Labels: refactor

#100 [refactor] 주문 처리 상태 enum으로 구현, 주문 취소시 상태만 변경#1
  src/main/java/com/back/domain/order/controller/OrderController.java
  src/main/java/com/back/domain/order/dto/OrderDto.java
  src/main/java/com/back/domain/order/dto/OrderDtoWithSpecific.java
  src/main/java/com/back/domain/order/entity/Order.java
  src/main/java/com/back/domain/order/entity/OrderStatus.java
  src/main/java/com/back/domain/order/service/OrderService.java
  src/test/java/com/back/domain/order/controller/OrderControllerTest.java
Labels: refactor

#101 [feat] 사용자 주문 전체 조회#1
  src/main/java/com/back/domain/member/member/controller/MemberController.java
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/member/member/service/MemberService.java
  src/main/java/com/back/domain/order/controller/OrderController.java
  src/main/java/com/back/domain/order/dto/OrderItemCreateReqBody.java
  src/main/java/com/back/domain/order/dto/UserOrderItemResponseDto.java
  src/main/java/com/back/domain/order/dto/UserOrderResponseBody.java
  src/main/java/com/back/domain/order/entity/Order.java
  src/main/java/com/back/domain/order/entity/OrderItem.java
  src/main/java/com/back/domain/order/service/OrderService.java
  src/main/resources/application.yml
  src/test/java/com/back/domain/member/member/controller/MemberControllerTest.java
Labels: feat

#102 [refactor] 메뉴 수정 기능 리팩토링#1
  src/main/java/com/back/domain/product/controller/ProductController.java
  src/main/java/com/back/domain/product/service/ProductService.java
Labels: refactor

#103 [feat] 주문 전체 조회(관리자 권한)#1
  src/main/java/com/back/domain/order/controller/AdmOrderController.java
  src/main/java/com/back/domain/order/controller/OrderController.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/test/java/com/back/domain/order/controller/AdmOrderControllerTest.java
  src/test/java/com/back/domain/order/controller/OrderControllerTest.java
Labels: feat

#106 [hotfix] 병합 후 테스트 케이스 실패 오류 수정
  src/main/java/com/back/domain/order/entity/Order.java
  src/test/java/com/back/domain/member/member/controller/MemberControllerTest.java
Labels: fix

#108 [feat]: 메뉴(상품)의 주문 가능 상태 변경#1
  src/main/java/com/back/domain/product/controller/ProductController.java
  src/main/java/com/back/domain/product/dto/ProductWithOrderable.java
  src/main/java/com/back/domain/product/service/ProductService.java
  src/test/java/com/back/domain/product/controller/ProductControllerTest.java
Labels: feat

#109 [feat] 주문 단건 조회(관리자 권한)#1
  src/main/java/com/back/domain/member/member/entity/Member.java
  src/main/java/com/back/domain/order/controller/AdmOrderController.java
  src/main/java/com/back/domain/order/controller/OrderController.java
  src/test/java/com/back/domain/order/controller/AdmOrderControllerTest.java
Labels: feat

#114 [feat] 주소 변경
  src/main/java/com/back/domain/member/address/controller/AddressController.java
  src/main/java/com/back/domain/member/address/dto/AddressDto.java
  src/main/java/com/back/domain/member/address/entity/Address.java
  src/main/java/com/back/domain/member/address/service/AddressService.java
  src/test/java/com/back/domain/member/address/controller/AddressControllerTest.java
Labels: feat

#116 [feat] 주문 처리 상태 변경(관리자 권한)
  src/main/java/com/back/domain/order/controller/AdmOrderController.java
  src/main/java/com/back/domain/order/entity/OrderStatus.java
  src/main/java/com/back/domain/order/service/OrderService.java
  src/test/java/com/back/domain/order/controller/AdmOrderControllerTest.java
Labels: feat

#118 [feat] 비밀번호 검증 엔드포인트 추가 #1
  src/main/java/com/back/domain/member/member/controller/MemberController.java
  src/main/java/com/back/global/initData/DevInitData.java
  src/main/java/com/back/global/initData/TestInitData.java
  src/test/java/com/back/domain/member/member/controller/MemberControllerTest.java
Labels: feat
